version: "3.8"

services:

  test_database:
    container_name: test_db
    image: mysql
    environment:
      MYSQL_USER: ogleh
      MYSQL_PASSWORD: 1122
      MYSQL_ROOT_PASSWORD: 1234,
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - test-node-networks
     
networks:
  test-node-networks: